var WORDS = [
["Abacus", " Frame With Balls For Calculating"],
["Abate", " To Lessen To Subside "],
["Abdication", " Giving Up Control Authority "],
["Aberration", " Straying Away From What Is Normal "],
["Abet", " Help/encourage Somebody (in Doing Wrong) "],
["Abeyance", " Suspended Action "],
["Abhor", " To Hate To Detest "],
["Abide", " Be Faithful To Endure "],
["Abjure", " Promise Or Swear To Give Up "],
["Abraded", " Rubbed Off Worn Away By Friction "],
["Abrogate", " Repeal Or Annul By Authority"],
["Abscond", " To Go Away Suddenly (to Avoid Arrest) "],
["Abstruse", " Difficult To Comprehend Obscure "],
["Abut", " Border On "],
["Abysmal", " Bottomless Extreme "],
["Acarpous", " Effete No Longer Fertile Worn Out "],
["Acclaimed", " Welcomed With Shouts And Approval"],
["Accolade", " Praise Approval "],
["Accretion", " The Growing Of Separate Things Into One "],
["Adamant", " Kind Of Stone Inflexible "],
["Admonitory", " Containing Warning "],
["Adorn", " Add Beauty Decorate "],
["Adulteration", " Making Unpure Poorer In Quality"],
["Affable", " Polite And Friendly"],
["Affinity", " Close Connection Relationship "],
["Aggravate", " Make Worse Irritate "],
["Agile", " Active Quick-moving "],
["Agog", " Eager/excited "],
["Ail", " Trouble Be Ill "],
["Alacrity", " Eager And Cheerful Readiness "],
["Alcove", " Recess/partially Enclosed Place"],
["Allegiance", " Duty Support Loyalty "],
["Alleviate", " Make (pain) Easier To Bear"],
["Alloy", " To Debase By Mixing With Something Inferior "],
["Aloof", " Reserved Indifferent "],
["Amalgamate", " Mix Combine Unite Societies "],
["Ambidextrous", " Able To Use The Left Hand Or The Right Equally Well "],
["Ambiguous", " Doubtful Uncertain "],
["Ambivalent", " Having Both Of Two Contrary Meanings "],
["Ameliorate", " Improve Make Better "],
["Amortize", " End (a Debt) By Setting Aside Money "],
["Anguish", " Severe Suffering "],
["Animosity", " Strong Dislike "],
["Antidote", " Medicine Used Against A Poison Or A Disease "],
["Antithetical", " Direct Opposing "],
["Apartheid", " Brutal Racial Discrimination "],
["Aplomb", " Self-confidence "],
["Apostate", " One Who Abandons Long-held Religious Or Political Convictions "],
["Apotheosis", " Deification Glorification To Godliness "],
["Appease", " Make Quiet Or Calm "],
["Apprehensive", " Grasping Understanding Fear Unhappy Feeling About Future "],
["Apprise", " Give Notice To Inform "],
["Approbation", " Approval "],
["Apropos", " Appropriate To The Situation Apt"],
["Apt", " Well-suited Quick-witted "],
["Arabesque", " A Complex Ornate Design "],
["Arboreal", " Of Connected With Trees "],
["Ardor", " Enthusiasm "],
["Arduous", " Steep Difficult Ascent Laborious "],
["Argot", " Jargon Slang "],
["Arrant", " In The Highest Degree "],
["Arrogance", " Proud Superior Manner Of Behaviour"],
["Articulate", " Speak Distinctly Connect By Joints"],
["Ascend", " Go Or Come Up "],
["Ascertain", " Get To Know "],
["Ascetic", " Practicing Self-denial Austere Stark "],
["Ascribe", " Consider To Be The Origin Of Or Belonging To "],
["Aseptic", " Surgically Clean "],
["Asperity", " Roughness Harshness Ill Temper Irritability"],
["Aspersion", " Slander "],
["Assail", " With Attack Violently "],
["Assiduous", " Diligent Hard-working Sedulous "],
["Assuage", " Make Something (pain Desire) Less"],
["Asterisk", " The Mark * (e.g.. Omitted Letters) "],
["Astringent", " Substance That Shrinks "],
["Astute", " Clever Quick At Seeing To Get An Advantage "],
["Atonement", " Repayment Death Of Jesus "],
["Attenuate", " Make Thin. Weaken Enervate "],
["Attune", " Bring Into Harmony"],
["Audacious", " Daring Foolishly Bold Impudent "],
["Augury", " Omen Sign "],
["August", " Majestic Venerable "],
["Auspicious", " Favorable Successful Prosperous "],
["Austere", " Severely Moral And Strict Simple And Plain "],
["Auxiliary", " Helping Supporting "],
["Aver", " Affirm Assert Prove Justify "],
["Aversion", " Strong Dislike "],
["Avid", " Eager Greedy "],
["Avow", " Admit. Declare Openly "],
["Baleful", " Harmful Ominous Causing Evil "],
["Balk", " Obstacle Purposely To Get On The Way Of "],
["Baneful", " Causing Harm Or Ruin Pernicious Destructive "],
["Barrage", " Artificial Obstacle Built Across A River "],
["Barren", " Not Good Enough Unable To Have Young Ones Without Value "],
["Bask", " In Enjoy Warmth And Light"],
["Beatify", " To Bless Make Happy Or Ascribe A Virtue To "],
["Bedizen", " To Adorn Especially In A Cheap Showy Manner "],
["Belabor", " Beat Hard "],
["Bellicose", " Belligerent Pugnacious Warlike "],
["Belligerent", " (person Nation) Waging War "],
["Benefactor", " Person Who Has Given Help"],
["Benevolence", " Wish Or Activity In Doing Good "],
["Benign", " Kind And Gentle Mild (climate)"],
["Bequest", " Arrangement To Give Something At Death "],
["Berate", " Scold Sharply "],
["Bereft", " Rob Or Dispossess Of Something (material) "],
["Bewilder", " Puzzle Confuse "],
["Bigot", " Stubborn Narrow-minded Person "],
["Bilge", " Bulge The Protuberance Of A Cask "],
["Blandishment", " Flattery Coaxing "],
["Blandness", " Polite Manner Comforting Uninteresting "],
["Blatant", " Noisy And Rough "],
["Blithe", " Cheerful Casual Carefree "],
["Bogus", " Sham Counterfeit Not Genuine "],
["Boisterous", " Loud Noisy Rough Lacking Restraint"],
["Bolster", " Give Greatly Needed Support "],
["Boorish", " Crude Offensive Rude "],
["Brash", " Hasty Rush Cheeky Saucy "],
["Brass", " Yellow Metal (mixing Copper And Zinc) "],
["Brazen", " Made Of Brass "],
["Breach", " Opening Broken Place Breaking "],
["Brittle", " Easily Broken "],
["Broach", " Bring Up Announce Begin To Talk About "],
["Brook", " To Tolerate Endure "],
["Buoyant", " Able To Float Light-hearted "],
["Burgeon", " Grow Forth Send Out Buds"],
["Burnish", " To Polish Rub To A Shine "],
["Cabal", " A Scheme Or Plot A Group Of Plotters "],
["Cadge", " To Beg To Get By Begging "],
["Cajole", " Use Flattery Or Deceit To Persuade "],
["Calipers", " Metal Supports Attached To The Legs Measuring Instrument "],
["Calumny", " Slander Aspersion "],
["Candid", " Frank Straight-forward "],
["Cant", " Insincere Talk/jargon "],
["Cantankerous", " Bad-tempered/quarrelsome "],
["Canvass", " Discuss Thoroughly Sort Of Touting"],
["Castigate", " To Chastise Correct By Punishing"],
["Castigation", " Severe Punishment "],
["Catalyst", " Substance That Causes Speeding Up"],
["Caustic", " Biting Sarcastic "],
["Censure", " Expression Of Blame Or Disapproval A Rebuke "],
["Centurion", " Leader Of A Unit Of 100 Soldiers "],
["Chary", " Cautious Wary "],
["Chastened", " Corrected Punished "],
["Chastisement", " Punishment "],
["Chauvinist", " A Blindly Devoted Patriot "],
["Chicanery", " Legal Trickery/false Argument"],
["Chisel", " Steel Tool For Shaping Materials"],
["Churl", " Bad-tempered Person "],
["Clamor", " Shout Complain With A Lot Of Noise "],
["Clientele", " Customers "],
["Clinch", " Come To Grips/settle Conclusively "],
["Cling", " To Resist Separation "],
["Clot", " Half-solid Lump Formed From Liquid"],
["Cloture", " Closing Device (in Parliament) To End A Debate By Voting "],
["Coagulation", " Change To A Thick And Solid State "],
["Coalescing", " Coming Together And Uniting Into One Substance "],
["Coax", " Get Somebody To Do Something By Kindness "],
["Coda", " Passage That Completes A Piece Of Music "],
["Coddle", " Treat With Care And Tenderness"],
["Coerce", " Compel To Force To Make Obedient "],
["Coeval", " Of The Same Period Coexisting"],
["Cogent", " Strong Convincing "],
["Cogitate", " Think Deeply Mediate "],
["Cognizant", " Being Fully Aware Of "],
["Colander", " Bowl-shaped Vessel With Many Holes Used To Drain Off Water "],
["Collusion", " Secret Agreement For A Deceitful Purpose "],
["Combustion", " Process Of Burning "],
["Commemorate", " Keep The Memory Of "],
["Commodious", " Having Plenty Of Space For What Is Needed "],
["Commuter", " Person Who Travels Regularly "],
["Complaisance", " Tending To Comply Obliging Willingness To Please "],
["Compunction", " Feeling Of Regret For One's Action "],
["Conceal", " Hide Keep Secret "],
["Conceit", " Over-high Opinion Of Too Much Pride "],
["Conciliatory", " Reconciling Soothing Comforting Mollifying "],
["Concord", " Agreement Or Harmony "],
["Concur", " Agree In Opinion Happen Together"],
["Condense", " Increase In Density Strength Make Laconic "],
["Condone", " Forgive "],
["Congeal", " Make Or Become Stiff And Solid "],
["Conjoin", " To Join Together "],
["Connoisseur", " A Person With Good Judgement (e.g.. In Art) "],
["Connotation", " Suggestion In Addition To "],
["Consequential", " Pompous Self Important "],
["Console", " Give Comfort Or Sympathy To"],
["Conspicuous", " Easily Seen Remarkable "],
["Consternation", " Surprise And Fear Dismay "],
["Constrain", " Compel "],
["Constrict", " Make Tight Or Smaller "],
["Consume", " Get To The End Of"],
["Consummate", " Perfect/make Perfect/complete "],
["Contemn", " To Scorn Or Despise "],
["Contentious", " Argumentative Pugnacious Combative Quarrelsome "],
["Contiguous", " Touching Neighboring Near "],
["Contrite", " Filled With Deep Sorrow For Wrongdoing "],
["Contumacious", " Insubordinate Rebellious "],
["Conundrum", " A Riddle Dilemma Enigma "],
["Conviction", " Convincing Firm Belief "],
["Convoke", " Call Together Summon "],
["Convoluted", " Complicated Coiled Twisted "],
["Cordial", " Warm And Sincere "],
["Cordon", " Line (of Police Acting As A Guard) "],
["Cornucopia", " Abundant Supply "],
["Corporeal", " Physical Of Or For The Body "],
["Correlate", " Have A Mutual Relation "],
["Corroboration", " Additional Strengthening Evidence "],
["Countenance", " To Favor Or Approve Of"],
["Counterfeit", " Forgery "],
["Countervail", " Counterbalance "],
["Covert", " Disguised "],
["Covetous", " Eagerly Desirous "],
["Cower", " Crouch Shrink Back "],
["Coy", " Shy/modest (esp Of A Girl) "],
["Crass", " Very Great (es. Stupidity) "],
["Cravat", " Piece Of Linen Worn As A Necktie "],
["Craven", " Cowardly "],
["Crease", " Line Made By Crushing White Line On The Ground In Cricket "],
["Credulity", " Too Great A Readiness To Believe Things "],
["Credulous", " Ready To Believe Things "],
["Crush", " Press Lose Shape Subdue Overwhelm"],
["Cryptic", " Secret With A Hidden Meaning"],
["Cumbersome", " Burdensome Heavy And Awkward To Carry "],
["Curmudgeon", " Bad-tempered Person "],
["Curriculum", " Course Of Study "],
["Cursory", " Quick Hurried "],
["Curtail", " Make Shorter Then Was Planned"],
["Dainty", " Pretty/delicate(food)/difficult To Please"],
["Daunt", " Intimidate Make Fearful "],
["Dawdler", " Person Who Is Slow Waste Of Time "],
["Dearth", " Shortage "],
["Debacle", " A Breakup Overthrow Sudden Disaster"],
["Decorum", " Propriety Properness "],
["Decree", " Order Given By Authority "],
["Decry", " Disapprove Of "],
["Defer", " Postpone Give Way (to Show Respect) "],
["Deferential", " Showing Respect "],
["Defiance", " Open Disobedience Or Resistance "],
["Delineate", " To Portray Depict Sketch Out"],
["Deluge", " Great Flood Heavy Rush Of Water "],
["Demagogue", " Person Appealing Not To Reasons"],
["Demur", " To Hesitate Raise Objections "],
["Denigrate", " Blacken Belittle Sully Defame "],
["Denouement", " An Outcome Or Solution The Unraveling Of A Plot "],
["Deplete", " Use Until None Remains "],
["Deposition", " Dethronement Depositing "],
["Deprave", " Make Morally Bad Corrupt "],
["Deprecate", " Protest Against Express Disapproval Of"],
["Dereliction", " Deserting And Leaving To Fall Into Ruins "],
["Derision", " Ridicule Mockery Deriding "],
["Derivative", " Unoriginal Obtained From Another Source"],
["Derogatory", " Insulting Tending To Damage "],
["Descry", " Catch Sight Of See Something In The Distance "],
["Desiccant", " Substance Used To Absorb Moisture"],
["Desuetude", " Cessation Of Use Disuse "],
["Desultory", " Aimless Haphazard Digressing At Random"],
["Deter", " Discourage Hinder "],
["Detraction", " Slandering Verbal Attack Aspersion "],
["Detumescence", " Diminishing Or Lessening Of Swelling"],
["Deviance", " Being Different In Moral Standards (from Normal) "],
["Dexterity", " Skill (esp. In Handling) "],
["Diaphanous", " Transparent Gauzy "],
["Diatribe", " Bitter And Violent Attack In Words "],
["Diffidence", " Shyness "],
["Dilate", " Speak Comprehensively Become Wider Large"],
["Disallow", " Refuse To Allow Or Accept As A Correct "],
["Discern", " See With An Effort But Clearly "],
["Discomfit", " Confuse Embarrass "],
["Disconcert", " Upset The Self-possession Of "],
["Discountenance", " Refuse To Approve Of "],
["Discourse", " Speech Lecture "],
["Discredit", " Refuse To Believe "],
["Discreet", " Careful/prudent "],
["Discrete", " Individually Distinct "],
["Disdain", " Look On With Contempt "],
["Disencumber", " Free From Encumbrance "],
["Disheveled", " Untidy "],
["Disingenuous", " Sophisticated Artful Trying To Deceive Cunning "],
["Disinter", " Dig Up From The Earth"],
["Dislodge", " Move Force From The Place Occupied "],
["Dismal", " Sad Gloomy Miserable "],
["Disparate", " Essentially Different "],
["Disproof", " Proof To The Contrary "],
["Dissemble", " Speak Or Behave So As To Hide Something (in Mind) "],
["Disseminate", " Distribute (esp. Ideas) "],
["Dissent", " Have A Different Opinion Refuse To Assent "],
["Dissolution", " Disintegration Looseness In Morals "],
["Distraught", " Distracted Violently Upset In Mind"],
["Divergence", " Getting Farther Apart From A Point "],
["Divestiture", " Taking Off Getting Rid Of Giving Up "],
["Divulge", " Make Known Something Secret "],
["Doggerel", " Trivial Poorly Constructed Verse "],
["Dogmatic", " Positive Certain Arbitrary Without Room For Discussion "],
["Dolt", " Stupid Fellow "],
["Dormant", " In A State Of Inactivity But Awaiting Development "],
["Dote", " Show Much Fondness Center One's Attention "],
["Drawl", " Slow Way Of Speaking "],
["Droll", " Jesting "],
["Drone", " Male Bee Person Who Isn't Self-employed "],
["Drowsiness", " Feeling Sleepy Half Asleep "],
["Dubious", " Feeling Doubt "],
["Dud", " No Use Person Something That Fails "],
["Dulcet", " Melodious Harmonious "],
["Dupe", " Cheat Make A Fool Of"],
["Duplicity", " Deliberate Deception "],
["Duress", " Threats To Compel Somebody "],
["Dwarf", " Person Or Somebody Much Below The Usual Size "],
["Dynamo", " A Generator Something That Produces Electric Current "],
["Earthenware", " Dishes Made Of Baked Clay"],
["Ebullience", " Exuberance Outburst Of Feeling "],
["Ebullient", " Overflowing With Enthusiasm Showing Excitement"],
["Ecumenical", " Representing The Whole Christian World"],
["Edacious", " Voracious Devouring "],
["Eddy", " Circular Or Spiral Movement (e.g.. Of Wind) "],
["Edible", " Fit To Be Eaten/not Poisonous "],
["Effete", " Infertile Worn Out Weak "],
["Efficacy", " Production Of A Desired Result"],
["Effluvia", " Outflow In A Stream Of Particles A Noxious Odor Or Vapor "],
["Effrontery", " Boldness Impudence Arrogance "],
["Egress", " Way Out Exit "],
["Elaborate", " Worked Out With Much Care In Great Detail "],
["Elegy", " A Lament A Melancholy Composition"],
["Elicit", " Draw Out "],
["Eloquence", " Fluent Speaking Skillful Use Of Language "],
["Emaciate", " Make Thin And Weak "],
["Embellish", " Make Beautiful "],
["Embezzle", " Use In A Wrong Way For One's Own Benefit "],
["Emote", " Stir Up Excite "],
["Empirical", " Relying On Experiment "],
["Encapsulate", " Enclose In Capsule "],
["Encomium", " Warm Or Glowing Praise Eulogy Panegyric "],
["Encumbrance", " Burden Things That Get On The Way Of "],
["Endearing", " Making Dear Or Liked "],
["Endemic", " Epidemic "],
["Endorse", " Write One's Name On The Back Of "],
["Enduring", " Lasting "],
["Enervate", " Weaken Deprive Of Strength Attenuate"],
["Engender", " Cause Produce Give Rise To"],
["Engrave", " Impress Deeply "],
["Engrossing", " Taken Up All The Time Or Attention Writing In Large Or Formal"],
["Engulf", " Swallow Up "],
["Enigma", " Something That Is Puzzling "],
["Enmity", " Hatred Being An Enemy "],
["Ensign", " Flag/badge "],
["Entangle", " Put Into Difficulties "],
["Enthral", " Please Greatly/enslave (fig)"],
["Entice", " Tempt Or Persuade"],
["Entreat", " Ask Earnestly "],
["Enunciate", " Pronounce (words)/express A Theory "],
["Enzyme", " Catalyst "],
["Epicurean", " Devoted To Pleasure (sensuous Enjoyment)"],
["Epistle", " Letter "],
["Epithet", " Adjective "],
["Epitome", " Brief Summary Representative Example A Typical Model "],
["Equable", " Steady Regular "],
["Equanimity", " Calmness Of Temperament "],
["Equilibrium", " State Of Being Balanced "],
["Equipoise", " Equal Distribution Of Weight Equilibrium"],
["Equivocal", " Having A Double Or Doubtful Meaning Suspicious "],
["Equivocate", " Try To Deceive By Equivocal Language "],
["Eradicate", " Get Rid Of Pull Up By The Roots "],
["Erratic", " Irregular In Behaviour Or Opinion"],
["Erudite", " Learned Scholarly "],
["Eschew", " Avoid "],
["Esoteric", " Abstruse Intended Only For A Small Circle Of "],
["Espouse", " Marry Give One's Support To"],
["Eulogy", " Formal Praise Panegyric "],
["Euphoria", " Elation State Of Pleasant Excitement"],
["Euthanasia", " Easy And Painless Death "],
["Evasive", " Tending To Evade"],
["Evince", " To Show Clearly To Indicate"],
["Evoke", " Call Up Bring Out "],
["Excoriation", " Severe Criticism "],
["Exculpate", " To Clear From A Charge Of Guilt "],
["Exhaustive", " Complete Thorough "],
["Exigency", " Emergency An Urgent Situation "],
["Exoneration", " Set Somebody Clear Free (e.g.. From Blame) "],
["Exorbitant", " Much Too High Or Great"],
["Expatiate", " To Roam Wander Freely "],
["Expedient", " Likely To Be Useful For A Purpose "],
["Expiation", " Ending Expiring "],
["Exploit", " Brilliant Achievement Develop Use Selfishly"],
["Expostulate", " Argue Earnestly To Dissuade Correct Or Protest "],
["Expurgate", " To Remove Obscenity Purify Censor"],
["Exscind", " To Cut Out Cut Away"],
["Extant", " Still In Existence "],
["Extempore", " Without Previous Thought Or Preparation "],
["Extenuate", " Reduce The Strength Of Lessen Seriousness Partially Excuse "],
["Extinct", " No Longer Active "],
["Extinguish", " End The Existence Of/wipe Or Put Out "],
["Extirpate", " To Destroy Exterminate Cut Out Exscind "],
["Extol", " Praise Highly "],
["Extort", " Obtain By Threats Violence "],
["Extralegal", " Outside The Law "],
["Extricable", " That Can Be Freed "],
["Extrovert", " Cheerful Person "],
["Exuberance", " State Of Growing Vigorously Being Full Of Life "],
["Facetious", " Humorous Funny Jocular "],
["Facile", " Easily Done "],
["Fallacious", " Based On Error "],
["Falter", " Waver/move In An Uncertain Manner "],
["Fatuous", " Without Sense Foolish Self-satisfaction "],
["Fawn", " Young Deer Try To Win Somebody's Favor "],
["Feckless", " Lacking Purpose Or Vitality Ineffective Careless "],
["Fecund", " Fertile "],
["Feint", " Pretend "],
["Felicitous", " Apt Suitably Expressed Well Chosen Apropos "],
["Felon", " Person Guilty Of Murder "],
["Ferment", " Substance Become Excited "],
["Ferocity", " Savage Cruelty "],
["Ferret", " Discover By Searching Search "],
["Fervid", " Showing Earnest Feeling "],
["Fervor", " Warmth Of Feelings Earnestness "],
["Fetid", " Stinking "],
["Fetter", " To Shackle Put In Chains"],
["Feud", " Bitter Quarrel Over A Long Period Of Time "],
["Fidelity", " Loyalty Accuracy "],
["Fidget", " Move Restlessly Make Nervous "],
["Figurehead", " Carved Image On The Prow Of A Ship "],
["Finesse", " Delicate Way Of Dealing With A Situation "],
["Finical", " Too Fussy About Food Clothing Etc. "],
["Finicky", " Finical "],
["Fission", " Splitting Or Division (esp. Of Cells) "],
["Fixate", " Stare At "],
["Flak", " Criticism/anti-aircraft Guns "],
["Flamboyant", " Brightly Colored Florid "],
["Flaunting", " Show Off Complacently "],
["Flax", " Pale Yellow (hair) A Plant"],
["Fledged", " Able To Fly Trained Experienced"],
["Fleet", " Number Of Ships Quick-moving "],
["Flinch", " Draw Move Back Wince "],
["Flop", " Fail/move/fall Clumsily "],
["Florid", " Very Much Ornamented Naturally Red (e.g.. Of Face) "],
["Flout", " Reject Mock To Go Against (as In Going Against Tradition) "],
["Fluke", " Lucky Stroke "],
["Fluster", " Make Nervous Or Confused "],
["Foible", " Defect Of Character (a Person Is Wrongly Proud) "],
["Foil", " Prevent From Carrying Out Contrast"],
["Foment", " Put Something Warm (to Lessen The Pain) "],
["Foolproof", " Incapable Of Failure Or Error "],
["Foppish", " Like A Man Who Pays Too Much Attention To His Clothes "],
["Forage", " Food For Horses And Cattle "],
["Forbear", " Refrain From Be Patient Ancestor"],
["Forbearance", " Patience Willingness To Wait "],
["Ford", " Shallow Place In A River (to Cross) "],
["Forestall", " Prevent By Taking Action In Advance Preempt "],
["Forfeit", " Suffer The Loss Of Something"],
["Forge", " Workshop For The Shaping Of Metal To Shape Metal Lead "],
["Forgery", " Counterfeit "],
["Forswear", " Renounce Disallow Repudiate "],
["Foster", " Nurture Care For "],
["Fracas", " Noisy Quarrel "],
["Fragile", " Easily Injured Broken Or Destroyed"],
["Fragrant", " Sweet-smelling "],
["Frantic", " Wildly Excited With Joy Pain Anxiety "],
["Frenetic", " Frantic Frenzied "],
["Fret", " Worry Irritation Wear Away "],
["Fringe", " Edge Ornamental Border Part Of Hair Over The Forehead "],
["Froward", " Intractable Not Willing To Yield Or Comply Stubborn "],
["Frugal", " Careful Economical "],
["Fulmination", " Bitter Protest "],
["Fulsome", " Disgusting Offensive Due To Excessiveness"],
["Gainsay", " To Deny To Oppose"],
["Garble", " Make Unfair Selection From Facts "],
["Garment", " Article Of Clothing "],
["Garner", " To Gather And Save To Store Up "],
["Garrulity", " Talkativeness "],
["Garrulous", " Too Talkative "],
["Gaucherie", " Socially Awkward Tactless Behavior "],
["Germane", " Relevant Pertinent To "],
["Gist", " The Point General Sense "],
["Glean", " Gather Facts In Small Quantities"],
["Glib", " Ready And Smooth But Not Sincere "],
["Glimmer", " Weak/unsteady Light "],
["Gloat", " Over Look At With Selfish Delight "],
["Glut", " Supply To Much Fill To Excess "],
["Gnaw", " Waste Away Bite Steadily "],
["Goad", " Something Urging A Person To Action "],
["Gorge", " Eat Greedily/narrow Opening With A Stream "],
["Gossamer", " Soft Light Delicate Material "],
["Gouge", " Tool For Cutting Grooves In Wood "],
["Grandiloquent", " Using Pompous Words"],
["Grave", " Serious Requiring Consideration "],
["Graze", " Touch Or Scrape Lightly In Passing "],
["Gregarious", " Living In Societies Liking The Company "],
["Grievous", " Causing Grief Or Pain Serious Dire Grave "],
["Grovel", " Crawl Humble Oneself "],
["Guile", " Deceit Cunning "],
["Gullible", " Easily Gulled "],
["Gush", " Burst Out Suddenly/talk Ardently "],
["Gust", " Outburst Of Feeling Sudden Rain Wind Fire Etc. "],
["Hack", " Cut Roughly Hired Horse "],
["Halcyon", " Calm And Peaceful"],
["Hallow", " To Make Holy Consecrate "],
["Harangue", " A Long Passionate Speech "],
["Harbinger", " Something Or Somebody That Foretells The Coming Of "],
["Harrow", " To Distress Create Stress Or Torment "],
["Haughty", " Arrogant Conceited "],
["Heed", " Attention/give Notice To"],
["Heinous", " Odious (of Crime) "],
["Heresy", " Belief Contrary To What Is Generally Accepted "],
["Hermetic", " Sealed By Fusion "],
["Heterogeneous", " Made Up Of Different Kinds"],
["Hew", " Make By Hard Work Cut (by Striking) "],
["Highbrow", " (person) With Superior Tastes "],
["Hirsute", " Hairy Shaggy "],
["Hoax", " Mischievous Trick Played On Somebody For A Joke "],
["Hoi", " Polloi The Masses The Rabble"],
["Hollow", " Not Soled With Hole "],
["Holster", " Leather Case For A Pistol"],
["Homiletics", " Act Of Preaching"],
["Hone", " Stone Used For Sharpening Tools"],
["Hoodwink", " Trick Mislead "],
["Hospitable", " Liking To Give Hospitality "],
["Hubris", " Arrogant Pride "],
["Hush", " Make Or Become Silent "],
["Husk", " Worthless Outside Part Of Anything"],
["Hypocrisy", " Falsely Making Oneself Appear To Be Good "],
["Iconoclast", " Person Who Attacks Popular Beliefs"],
["Idiosyncrasy", " Personal Mannerism "],
["Idolatry", " Excessive Admiration Of "],
["Idyll", " A Carefree Episode Or Experience"],
["Ignoble", " Dishonorable Common Undignified "],
["Ignominious", " Shameful Dishonorable Undignified Disgraceful "],
["Illicit", " Unlawful Forbidden "],
["Imbroglio", " Complicated And Embarrassing Situation "],
["Immaculate", " Pure Faultless "],
["Imminent", " Likely To Come Or Happen Soon "],
["Immutable", " That Cannot Be Changed "],
["Impair", " Worsen Diminish In Value "],
["Impassive", " Unmoved Feeling No Sign Of Passion "],
["Impecunious", " Having Little Or No Money"],
["Impede", " Hinder Get In The Way Of "],
["Impediment", " Something That Hinders (e.g. Stammer)"],
["Impending", " Imminent Being About To Happen Expected "],
["Imperative", " Urgent Essential "],
["Imperious", " Commanding Haughty Arrogant "],
["Impermeable", " That Cannot Be Permeated "],
["Imperturbable", " Calm Not Capable Of Being Excited "],
["Impervious", " Not Allowing To Pass Through (of Materials) "],
["Imperviousness", " Haughty Arrogant Commanding "],
["Impetuous", " Having Sudden Energy Impulsive Thrusting Ahead Forceful "],
["Impiety", " Lack Of Reverence Or Dutifulness"],
["Implacable", " Incapable Of Being Placated Unpleasable"],
["Implicate", " Show That Somebody Has A Share "],
["Implicit", " Implied Though Not Plainly Expressed"],
["Implosion", " Collapse Bursting Inward "],
["Importune", " Beg Urgently Solicit (of A Prostitute) "],
["Imprecation", " An Invocation Of Evil A Curse "],
["Impromptu", " Without Preparation "],
["Impudent", " Rash Indiscreet "],
["Impugned", " Challenged To Be Doubted "],
["Impute", " To Attribute To A Cause Or Source Ascribe "],
["Inadvertent", " Not Paying Proper Attention "],
["Inane", " Silly Senseless "],
["Inasmuch", " Since Because "],
["Incense", " Make Angry "],
["Incessant", " Often Repeated Continual "],
["Inchoate", " Not Yet Fully Formed Rudimentary Elementary "],
["Incipient", " Beginning "],
["Incise", " Engrave Make A Cut In"],
["Incite", " Stir Up Rouse "],
["Inclined", " Directing The Mind In A Certain Direction "],
["Incongruous", " Out Of Place Not In Harmony Or Agreement "],
["Incorrigibility", " Cannot Be Cured Or Corrected"],
["Incredulous", " Skeptical Unwilling To Believe "],
["Inculcate", " Fix Firmly By Repetition "],
["Incumbents", " Official Duties "],
["Incursion", " A Raid A Sudden Attack"],
["Indefatigability", " Not Easily Exhaustible Tirelessness "],
["Indelible", " That Cannot Be Rubbed Out"],
["Indigence", " Poverty "],
["Indigenous", " Native "],
["Indistinct", " Not Easily Heard Seen Clearly Marked "],
["Indolence", " Laziness "],
["Indomitable", " Not Easily Discouraged Or Subdued"],
["Indulge", " Gratify Give Way To Satisfy Allow Oneself "],
["Indulgent", " Inclined To Indulge "],
["Ineffable", " To Great To Be Described In Words "],
["Ineluctable", " Certain Inevitable "],
["Inept", " Unskillful Said Or Done At The Wrong Time "],
["Ineptitude", " Quality Of Being Unskillful "],
["Inferno", " Hell "],
["Infuriate", " Fill With Fury Or Rage"],
["Infuse", " Put Pour Fill "],
["Ingenuous", " Naive Young Artless Frank Honest Sincere "],
["Ingest", " Take In By Swallowing "],
["Inimical", " Harmful Or Friendly "],
["Inimitable", " Defying Imitation Unmatchable "],
["Innocuous", " Causing No Harm "],
["Inscrutable", " Incapable Of Being Discovered Or Understood "],
["Insensible", " Unconscious Unresponsive Unaffected "],
["Insinuate", " Suggest Unpleasantly Make A Way For Something Gently "],
["Insipid", " Without Taste Or Flavor "],
["Insouciant", " Unconcerned Carefree "],
["Insularity", " Narrow-mindedness Isolated "],
["Insurrection", " Rising Of People To Open Resistance To "],
["Interdict", " Prohibit Forbid "],
["Interim", " As An Installment "],
["Intersperse", " Place Here And There "],
["Intransigence", " Unwillingness To Compromise Stubbornness Intractability"],
["Intransigent", " Uncompromising "],
["Intrepid", " Fearless Brave Undaunted "],
["Introspection", " Examining One's Own Thoughts And Feelings "],
["Inundate", " Flood Cover By Overflowing "],
["Inured", " Accustomed To Adapted "],
["Invective", " Abusive Language Curses "],
["Inveigh", " To Attack Verbally Denounce Deprecate"],
["Inveterate", " Deep-rooted. Long-established "],
["Invincible", " Too Strong To Be Defeated "],
["Involute", " Complex "],
["Irascible", " Irritable Easily Angered "],
["Irate", " Angry "],
["Ire", " Anger "],
["Irksome", " Tiresome "],
["Irresolute", " Hesitating Undecided "],
["Irrevocable", " Final And Unalterable "],
["Itinerate", " To Travel From Place To Place To Peregrinate "],
["Jabber", " Talk Excitedly Utter Rapidly "],
["Jibe", " Gibe Make Fun Of "],
["Jocular", " Meant As A Joke "],
["Judicious", " Sound In Judgment Wise "],
["Knit", " Draw Together Unite Firmly "],
["Labyrinthine", " To Entangle The State Of Affairs "],
["Lachrymose", " Causing Tears Tearful "],
["Lackluster", " (of Eyes) Dull "],
["Lament", " Show Feel Great Sorrow "],
["Lassitude", " Weariness Tiredness "],
["Latent", " Present But Not Yet Active Developed Or Visible "],
["Laudatory", " Expressing Or Giving Praise "],
["Lavish", " Giving Or Producing Freely Liberally Or Generously "],
["Legacy", " Something Handed Down From Ancestors"],
["Levee", " Formal Reception/embankment "],
["Levity", " Lack Of Seriousness"],
["Libel", " Statement That Damages Reputation "],
["Liberality", " Free Giving Generosity "],
["Libertine", " Immoral Person "],
["Lien", " Legal Claim Until A Debt On It Is Repaid "],
["Limn", " Paint Portray "],
["Limp", " Lacking Strength Walking Unevenly "],
["Lionize", " Treat As A Famous Person "],
["Lithe", " Bending Twisting "],
["Loll", " Rest To Sit Or Stand In A Lazy Way Hang (dog's Tongue)"],
["Lope", " Move Along With Long Strides "],
["Loquacious", " Talkative Garrulous "],
["Lucubrate", " Write In Scholarly Fashion "],
["Luculent", " Easily Understood Lucid Clear "],
["Lugubrious", " Mournful Excessively Sad "],
["Lull", " Become Quiet Or Less Active"],
["Lumber", " Move In A Clumsy/noisy Way "],
["Luminary", " Star Light-giving Body "],
["Lurk", " Be Out Of View Ready To Attack "],
["Lustrous", " Being Bright Polished "],
["Macabre", " Gruesome Suggesting Death "],
["Macerate", " Make Or Become Soft By Soaking In Water "],
["Machination", " Plot Scheme (esp. Evil) "],
["Maladroit", " Tactless Clumsy "],
["Malapropism", " Misuse Of A Word (for One That Resembles It) "],
["Malevolence", " Wishing To Do Evil "],
["Malign", " Injurious Speak Ill Of Somebody Tell Lie "],
["Malinger", " To Fake Illness Or Injury In Order To Shirk A Duty "],
["Malleable", " Yielding Easily Shaped Moldable Adapting"],
["Manacle", " Chains For The Hands Or Feet "],
["Massacre", " Cruel Killing Of A Large Number Of People "],
["Matriculation", " Be Admitted Enter A University As A Student "],
["Maudlin", " Sentimental In A Silly Or Tearful Way "],
["Maul", " Hurt By Rough Handling "],
["Maverick", " Rebel Nonconformist "],
["Mellifluous", " Sweetly Flowing "],
["Mendacity", " Dishonesty "],
["Mendicant", " A Beggar "],
["Mercurial", " Quick Changeable In Character Fleeting"],
["Meretricious", " Attractive On The Surface But Of Little Value "],
["Mesmerize", " Hypnotize "],
["Meticulous", " Giving Great Attention To Details"],
["Mettle", " Quality Of Endurance Or Courage"],
["Mettlesome", " Courageous High-spirited "],
["Middling", " Fairly Good But Not Very Good "],
["Minatory", " Menacing Threatening "],
["Mince", " Pronounce Or Speak Affectedly Euphemize"],
["Misanthrope", " Person Who Hates Mankind "],
["Mischievous", " Harmful Causing Mischief "],
["Miser", " Person Who Loves Wealth And Spends Little "],
["Misogynist", " One Who Hates Women/females "],
["Moderation", " Quality Of Being Limited Not Extreme "],
["Mollify", " Make Calmer Or Quieter "],
["Molt", " Moult Lose Hair Feathers Before New Growing "],
["Morbid", " Diseased Unhealthy (e.g.. About Ideas)"],
["Morose", " Ill-tempered Unsocial "],
["Muffler", " Cloth Worn Round The Neck/silencer "],
["Multifarious", " Varied Motley Greatly Diversified "],
["Mundane", " Worldly As Opposed To Spiritual Commonplace Everyday "],
["Myriad", " Very Great Number "],
["Nadir", " Lowest Weakest Point "],
["Nascent", " Coming Into Existence Emerging "],
["Nebulous", " Cloud-like Hazy Vague Indistinct "],
["Negligent", " Taking Too Little Care "],
["Neophyte", " Person Who Has Been Converted To A Belief "],
["Nexus", " A Connection Tie Or Link"],
["Nibble", " Show Some Inclination To Accept (an Offer) "],
["Noisome", " Offensive Disgusting (smell) "],
["Nonchalant", " Not Having Interest "],
["Nonplused", " Greatly Surprised "],
["Nostrum", " A Quack Remedy An Untested Cure "],
["Noxious", " Harmful "],
["Nugatory", " Trifling/worthless "],
["Obdurate", " Hardened And Unrepenting Stubborn Inflexible"],
["Obfuscate", " To Darken Make Obscure Muddle"],
["Oblivious", " Unaware Having No Memory "],
["Obloquy", " Abusively Detractive Language Sharp Criticism Vituperation "],
["Obsequious", " Too Eager To Obey Or Serve "],
["Obstreperous", " Noisy Loud "],
["Obtain", " To Be Established Accepted Or Customary "],
["Obtrusive", " Projecting Prominent Undesirably Noticeable "],
["Obtuse", " Blunt/stupid "],
["Obviate", " To Make Unnecessary Get Rid Of "],
["Occluded", " Blocked Up "],
["Odious", " Repulsive Hateful "],
["Odium", " Contempt Dislike Aversion "],
["Odor", " Smell Favor Reputation "],
["Officious", " Too Eager Or Ready To Help Offer Advice "],
["Ominous", " Threatening "],
["Onerous", " Needing Effort Burdensome "],
["Opaqueness", " Dullness/not Allowing Light To Pass Through "],
["Opprobrious", " Showing Scorn Or Reproach "],
["Ossify", " To Turn To Bone To Settle Rigidly Into An Idea "],
["Ostensible", " Seeming Appearing As Such Professed"],
["Ostentation", " Display To Obtain Admiration Or Envy "],
["Ostracism", " Shut Out From Society Refuse To Meet Talk "],
["Overhaul", " Examine Thoroughly To Learn About The Condition "],
["Overweening", " Presumptuously Arrogant Overbearing Immoderate Being A Jerk "],
["Paean", " Song Of Praise Or Triumph"],
["Palate", " Roof Of The Mouth Sense Of Taste "],
["Palatial", " Magnificent "],
["Palliate", " Lessen The Severity Of "],
["Palpability", " Can Be Felt Touched Understood"],
["Palpitate", " Tremble Beat Rapidly And Irregularly"],
["Panegyric", " Formal Praise Eulogy "],
["Paradigm", " A Model Example Or Pattern"],
["Parenthesis", " Sentence Within Another One Something Separated "],
["Pariah", " An Outcast A Rejected And Despised Person "],
["Parsimonious", " Too Economical Miserly "],
["Partisan", " One-sided Committed To A Party Biased Or Prejudiced "],
["Patron", " Regular Customer Person Who Gives Support "],
["Paucity", " Scarcity A Lacking Of "],
["Peccadillo", " Small Sin Small Weakness In One's Character "],
["Pedantic", " Bookish Showing Off Learning "],
["Pedestrian", " Commonplace Trite Unremarkable "],
["Pellucid", " Transparent Easy To Understand "],
["Penchant", " Strong Inclination A Liking "],
["Penitent", " Feeling Or Showing Regret "],
["Penurious", " Poor/stingy "],
["Penury", " Extreme Poverty "],
["Peregrination", " Traveling About Wandering "],
["Peremptory", " Urgent Imperative Unchallengeable Ending Debate"],
["Perfidious", " Treacherous Faithless "],
["Perfidy", " Treachery Breaking Of Faith "],
["Perfunctory", " Done As A Duty Without Care "],
["Perilous", " Dangerous "],
["Peripatetic", " Wandering "],
["Perish", " Be Destroyed Decay "],
["Perjury", " Willful False Statement Unlawful Act"],
["Permeate", " Spread Into Every Part Of"],
["Pernicious", " Harmful Injurious "],
["Perpetrate", " Be Guilty Commit (a Crime)"],
["Personable", " Pleasing In Appearance Attractive "],
["Perspicacity", " Quick Judging And Understanding "],
["Pertain", " Belong As A Part Have Reference "],
["Pest", " Destructive Thing Or A Person Who Is Nuisance "],
["Petrified", " Taken Away Power (to Think Feel Act) "],
["Petrify", " To Make Hard Rocklike "],
["Petrous", " Like A Rock Hard Stony"],
["Petulant", " Unreasonably Impatient "],
["Philistine", " A Smug Ignorant Person One Who Lacks Knowledge "],
["Phlegmatic", " Calm Sluggish Temperament Unemotional "],
["Picaresque", " Involving Clever Rogues Or Adventurers"],
["Pied", " Of Mixed Colors "],
["Pinch", " Be Too Tight Take Between The Thumb And Finger "],
["Pine", " Waste Away Through Sorrow Or Illness "],
["Pious", " Dutiful To Parents Devoted To Religion "],
["Piquant", " Agreeably Pungent Stimulating "],
["Pique", " Hurt The Pride Or Self-respect Stir (curiosity) "],
["Pitfall", " Covered Hole As A Trap Unsuspected Danger "],
["Pith", " Essential Part Force Soft Liquid Substance "],
["Pivotal", " Of Great Importance (others Depend On It) "],
["Placate", " Soothe Pacify Calm "],
["Plaintive", " Mournful Melancholy Sorrowful "],
["Plaque", " Flat Metal On A Wall As A Memorial "],
["Platitude", " A Trite Or Banal Statement Unoriginality "],
["Plea", " Request "],
["Plead", " Address A Court Of Law As An Advocate "],
["Plethora", " Glut "],
["Pliant", " Pliable Easily Bent Shaped Or Twisted "],
["Plod", " Continue Doing Something Without Resting"],
["Pluck", " Pull The Feathers Off Pick (e.g.. Flowers) "],
["Plumb", " Get To The Root Of"],
["Plummet", " Fall Plunge Steeply "],
["Plunge", " Move Quickly Suddenly And With Force "],
["Poignant", " Deeply Moving Keen "],
["Poncho", " Large Piece Of Cloth "],
["Ponderous", " Heavy Bulky Dull "],
["Portent", " Omen Marvelous Threatening "],
["Precarious", " Uncertain Risky Dangerous "],
["Precepts", " Rules Establishing Standards Of Conduct"],
["Preclude", " Prevent Make Impossible "],
["Precursory", " Preliminary Anticipating "],
["Predilection", " Special Liking Mental Preference "],
["Predominate", " Have More Power Than Others"],
["Preen", " Tidy/show Self-satisfaction "],
["Premature", " Doing Or Happening Something Before The Right Time "],
["Preponderance", " Greatness In Number Strength Weight"],
["Presage", " Warning Sign "],
["Presumption", " Arrogance "],
["Preternatural", " Not Normal Or Usual "],
["Prevalent", " Common "],
["Prevaricate", " To Equivocate To Stray From The Truth "],
["Prim", " Neat Formal "],
["Pristine", " Primitive Unspoiled Pure As In Earlier Times Unadulterated "],
["Probity", " Uprightness Incorruptibility Principle "],
["Proclivity", " Inclination "],
["Procrastination", " Keeping On Putting Off "],
["Prodigal", " Wasteful Reckless With Money "],
["Prodigious", " Enormous Wonderful "],
["Profane", " Worldly Having Contempt For God"],
["Profligacy", " Shameless Immorality "],
["Profligate", " Wasteful Prodigal Licentious Extravagant "],
["Profundity", " Depth "],
["Profuse", " Abundant/lavish "],
["Proliferate", " Grow Reproduce By Rapid Multification"],
["Prolix", " Tiring Because Too Long "],
["Prone", " Prostrate Inclined To (undesirable Things)"],
["Propagation", " Increasing The Number Spreading Extending"],
["Propinquity", " Nearness In Time Or Place Affinity Of Nature "],
["Propitiatory", " Conciliatory Appeasing Mitigating "],
["Propitious", " Auspicious Presenting Favorable Circumstances "],
["Prosaic", " Everyday Mundane Commonplace Trite Pedestrian"],
["Proscribe", " Denounce As Dangerous "],
["Protracted", " Prolonged "],
["Provident", " Frugal Looking To The Future"],
["Provisional", " Of The Present Time Only"],
["Provoke", " Make Angry Vax "],
["Prudence", " Careful Forethought "],
["Prudish", " Easily Shocked Excessively Modest "],
["Prune", " Dried Plum Silly Person "],
["Pry", " Get Something Inquire Too Curiously"],
["Pucker", " Wrinkle "],
["Pugnacious", " Fond Of In The Habit Of Fighting "],
["Puissance", " Strength "],
["Punctilious", " Precise Paying Attention To Trivialities"],
["Pundit", " Pedant Authority On A Subject"],
["Pungency", " Sharpness Stinging Quality "],
["Purvey", " Provide Supply "],
["Pusillanimous", " Cowardly Craven "],
["Putrefaction", " Becoming Rotten "],
["Pyre", " Large Pile Of Wood For Burning "],
["Quack", " Person Dishonestly Claiming To Something"],
["Quaff", " Drink Deeply "],
["Quail", " Lose Courage Turn Frightened "],
["Qualm", " Feeling Of Doubt Temporary Feeling Of Sickness "],
["Quandary", " State Of Doubt Or Perplexity "],
["Quell", " Suppress Subdue "],
["Quibble", " Try To Avoid By Sophistication"],
["Quiescence", " State Of Being Passive/motionless "],
["Quiescent", " At Rest Dormant Torpid "],
["Quirk", " Habit Or Action Peculiar To Somebody Or Something "],
["Quixotic", " Generous Unselfish "],
["Quotidian", " Banal Everyday "],
["Rabble", " Mob Crowd The Lower Classes Of Populace "],
["Raconteur", " Person Who Tells Anecdotes "],
["Raffish", " Low Vulgar Base Tawdry "],
["Ramify", " To Be Divided Or Subdivided To Branch Out "],
["Rancorous", " Feeling Bitterness Spitefulness "],
["Rant", " Use Extravagant Language "],
["Rapacious", " Greedy (esp For Money) "],
["Rarefy", " To Make Thin To Make Less Dense To Purify Or Refine "],
["Rave", " Act With Excessive Enthusiasm "],
["Reactionary", " Opposing Progress "],
["Rebuff", " Snub "],
["Recalcitrant", " Disobedient "],
["Recant", " Take Back As Being False Give Up "],
["Recast", " Cast Or Fashion Anew "],
["Recidivism", " Relapse Into Antisocial Or Criminal Behavior "],
["Reciprocity", " Granting Of Privileges In Return For Similar "],
["Recitals", " A Number Of Performance Of Music "],
["Recluse", " Person Who Lives Alone And Avoids People "],
["Recompense", " Make Payment To Reward Punish"],
["Reconcile", " Settle A Quarrel Restore Peace"],
["Recondite", " Little Known Abstruse "],
["Recreancy", " Cowardice A Cowardly Giving Up"],
["Recuperate", " Become Strong After Illness Loss Exhaustion "],
["Redeem", " Get Back By Payment Compensate"],
["Redoubtable", " Formidable Causing Fear "],
["Refine", " Make Or Become Pure Cultural"],
["Refractory", " Stubborn Unmanageable Untractable "],
["Refulgent", " Shining Brilliant "],
["Regale", " To Delight Or Entertain To Feast "],
["Regicide", " Crime Of Killing A King"],
["Reiterate", " Say Or Do Again Several Times "],
["Rejuvenation", " Becoming Young In Nature Or Appearance "],
["Relapse", " Fall Back Again "],
["Remonstrate", " To Protest Object "],
["Render", " Deliver Provide Represent "],
["Renovate", " Restore Something To Better Condition"],
["Renowned", " Celebrated Famous "],
["Repast", " Meal "],
["Repel", " Refuse To Accept/cause Dislike "],
["Repine", " At Be Discontented With "],
["Reproach", " Scold Upbraid "],
["Reprobate", " Person Hardened In Sin One Devoid Of Decency "],
["Repudiate", " Disown Refuse To Accept Or Pay "],
["Repulsive", " Causing A Feeling Of Disgust"],
["Requite", " Repay Give In Return "],
["Rescind", " Repeal/annul/cancel "],
["Resigned", " Unresisting Submissive "],
["Resilience", " Quality Of Quickly Recovering The Original Shape "],
["Resort", " To Frequently Visit "],
["Restive", " Refusing To Move Reluctant To Be Controlled "],
["Resuscitation", " Coming Back To Consciousness "],
["Retard", " Check Hinder "],
["Reticent", " Reserved Untalkative Silent Taciturn "],
["Revere", " Have Deep Respect For "],
["Reverent", " Feeling Or Showing Deep Respect "],
["Riddle", " Puzzling Person Or Thing "],
["Rift", " Split Crack Dissension "],
["Rivet", " Fix Take Up Secure Metal Pin "],
["Roll", " Call Calling Of Names "],
["Rotund", " Rich And Deep Plump And Round "],
["Ruffian", " Violent Cruel Man "],
["Rumple", " Make Rough "],
["Sagacious", " Having Sound Judgment Perceptive Wise Like A Sage "],
["Salacious", " Obscene "],
["Salubrious", " Healthful "],
["Salutary", " Remedial Wholesome Causing Improvement "],
["Sanctimony", " Self-righteousness Hypocritical With False Piety"],
["Sanction", " Approval (by Authority) Penalty "],
["Sanguine", " Cheerful Confident Optimistic "],
["Sanity", " Health Of Mind Soundness Of Judgement "],
["Sash", " Long Strip Worn Round The Waist "],
["Satiate", " Satisfy Fully "],
["Saturnine", " Gloomy Dark Sullen Morose "],
["Savant", " Person Of Great Learning "],
["Savor", " Taste Flavor Something "],
["Sawdust", " Tiny Bits Of Wood "],
["Scabbard", " Sheath For The Blade "],
["Scent", " Smell (esp Pleasant) "],
["Scorch", " Become Discolored/dry Up/go At High Speed "],
["Scribble", " Write Hastily "],
["Scurvy", " Mean Contemptible "],
["Secular", " Material (not Spiritual) Living Outside Monasteries "],
["Sedulous", " Persevering "],
["Seminal", " Like A Seed Constituting A Source Originative "],
["Sententious", " Short And Pithy Full Of Maxims/proverbs "],
["Sequence", " Succession Connected Line Of "],
["Sere", " Make Hard And Without Feeling "],
["Sermon", " Reproving A Person For His Faults "],
["Serrated", " Having A Toothed Edge "],
["Serration", " Having A Toothed Edge "],
["Servile", " Like A Slave Lacking Independence"],
["Sever", " Break Off "],
["Severance", " Severing "],
["Shallow", " Little Depth Not Earnest "],
["Shard", " Piece Of Broken Earthenware "],
["Sheath", " Cover For The Blade Of A Weapon Or A Tool "],
["Shrewd", " Astute Showing Sound Judgement "],
["Shrill", " Sharp Piercing "],
["Shun", " Keep Away From Avoid "],
["Shunt", " Send From One Track To Another Lay Aside Evade Discussion "],
["Sidestep", " Step To One Side "],
["Simper", " (give A) Silly/self-conscious Smile "],
["Sinuous", " Winding Undulating Serpentine "],
["Skiff", " Small Boat "],
["Skit", " Short Piece Of Humorous Writing"],
["Slack", " Sluggish Dull Not Tight "],
["Slake", " To Assuage To Satisfy Allay"],
["Slate", " King Of Blue-grey Stone Propose Criticize "],
["Sluggard", " Lazy Slow-moving Person "],
["Slur", " Join Sounds/words (indistinct)"],
["Smolder", " Burn Slowly Without Flame "],
["Snare", " Trap "],
["Snub", " Treat With Contempt"],
["Soar", " Rise Fly High "],
["Sober", " Self-controlled "],
["Sobriety", " Quality Or Condition Of Being Sober "],
["Sodden", " Soaked Saturated "],
["Soggy", " Heavy With Water "],
["Solvent", " Of The Power Of Forming A Solution "],
["Somatic", " Of The Body "],
["Soot", " Black Powder In Smoke "],
["Sophisticated", " Complex Subtle Refined "],
["Sophistry", " Fallacious Reasoning Faulty Logic "],
["Sophomoric", " Self-assured Though Immature Affected Bombastic Overblown "],
["Soporific", " Producing Sleep "],
["Sordid", " Wretched Comfortless Contemptible "],
["Spear", " Weapon With A Metal Point On A Long Shaft "],
["Specious", " Illogical Of Questionable Truth Or Merit "],
["Splenetic", " Bad-tempered Irritable "],
["Splice", " Join (two Ends) "],
["Sponge", " Porous Rubber For Washing Live At Once Expense "],
["Spurious", " False Counterfeit "],
["Spurn", " Have Nothing To Do Reject Or Refuse "],
["Squalid", " Foul Filthy "],
["Squander", " Spend Wastefully "],
["Squat", " Crouch/settle Without Permission"],
["Stanch", " To Stop The Flow Of A Fluid "],
["Steeply", " Rising Or Falling Sharply "],
["Stentorian", " Extremely Loud And Powerful "],
["Stickler", " Person Who Insists On Importance Of Something "],
["Stigma", " Mark Of Shame Or Disgrace"],
["Stigmatize", " Describe Somebody Scornfully "],
["Sting", " Something Sharp "],
["Stingy", " Spending Using Unwillingly "],
["Stint", " To Be Thrifty To Set Limits "],
["Stipple", " Paint With Dots"],
["Stipulate", " State Or Put Forward As A Necessary Condition "],
["Stolid", " Showing No Emotion Impassive "],
["Stray", " Wander Lose One's Way "],
["Streak", " Long Thin Move Very Fast"],
["Striated", " Striped Grooved Or Banded "],
["Stride", " Walk With Long Steps "],
["Strut", " A Supporting Bar "],
["Stygian", " Hence Dark Gloomy "],
["Stymie", " To Hinder Obstruct Or Block"],
["Subdue", " Overcome Bring Under Control "],
["Sublime", " Extreme Astounding "],
["Submerge", " Put Under Water Liquid Sink Out Of Sight "],
["Suborn", " Induce By Bribery Or Something To Commit Perjury "],
["Subpoena", " Written Order Requiring A Person To Appear In A Low Court "],
["Substantiation", " Giving Facts To Support (statement) "],
["Subsume", " Include Under A Rule "],
["Succor", " Assistance Relief In Time Of Distress "],
["Suffice", " Be Enough "],
["Suffocate", " Cause Or Have Difficulty In Breathing "],
["Sullied", " To Be Stained Or Discredited"],
["Summarily", " Briefly Without Delay "],
["Sumptuous", " Magnificent "],
["Sundry", " Various Miscellaneous Separate "],
["Supercilious", " Disdainful Characterized By Haughty Scorn"],
["Superfluous", " More Then Is Needed Or Wanted "],
["Superimpose", " Put Something On The Top"],
["Supersede", " Take The Place Of "],
["Supine", " Lying On The Back Slow To Act Passive "],
["Suppliant", " Asking Humbly Beseeching "],
["Supplicate", " Make A Humble Petition To"],
["Suppress", " Prevent From Being Known Put An End To "],
["Surcharge", " Additional Load/charge "],
["Surfeit", " Satiate Feed To Fulness Or To Excess "],
["Susceptibility", " Sensitiveness "],
["Swerve", " Change Direction Suddenly"],
["Sycophant", " Person Who Flatter To The Rich And Powerful "],
["Synopsis", " Summary Or Outline "],
["Taciturn", " Untalkative Silent "],
["Tadpole", " Form Of A Frog When It Leaves The Egg "],
["Talon", " Claw Of A Bird Of Prey "],
["Tamp", " Tap Or Drive Down By Repeated Light Blows "],
["Tamper", " Interfere With "],
["Tangential", " Suddenly Changeable "],
["Tarnished", " Lost Brightness "],
["Tassel", " Bunch Of Threads"],
["Taunt", " Contemptuous Reproach Hurtful Remark "],
["Taut", " Tightly Stretched "],
["Tautology", " A Repetition A Redundancy "],
["Tawdry", " Cheap Gaudy Showy Tacky "],
["Teetotal", " Oppose To Alcohol "],
["Temerity", " Boldness Brashness Intrepidness "],
["Temperance", " Abstinence From Alcohol Self-control Moderation"],
["Temperate", " Showing Self-control "],
["Tenacity", " Firmness Persistency Adhesiveness Tending To Hang On "],
["Tenuous", " Insubstantial Flimsy Weak "],
["Tepid", " Lukewarm "],
["Terse", " Brief And To The Point"],
["Testiness", " Witness/evidence "],
["Thrift", " Care Economy Thriving Prosperous "],
["Thwart", " Obstruct/frustrate "],
["Timid", " Shy Easily Frightened "],
["Timorous", " Fearful Timid Afraid "],
["Toady", " Obsequious Flatterer "],
["Tonic", " Something Giving Strength Or Energy"],
["Topple", " Be Unsteady And Overturn "],
["Torment", " Severe Pain Or Suffering "],
["Torpid", " Sleeping Sluggish Lethargic Dormant "],
["Torque", " Twisting Force Causing Rotation "],
["Tortuous", " Devious/not Straightforward "],
["Tout", " Person Who Worries Others To Buy Something To Use His Service "],
["Tractable", " Easily Controlled Or Guided "],
["Transgress", " Break Go Beyond (a Limit)"],
["Transient", " Temporary Fleeting "],
["Transitory", " Brief "],
["Travesty", " Parody/imitation "],
["Trenchant", " Forceful Effective Vigorous Extremely Perceptive Incisive "],
["Trepidation", " Alarm Excited State Of Mind"],
["Trickle", " Flow In Drops"],
["Trifling", " Unimportant "],
["Trite", " Not New "],
["Truce", " (agreement) Stop Of Fighting For A Time "],
["Truculence", " Aggressiveness Ferocity "],
["Trudge", " Walk Heavily "],
["Turbid", " Muddy Having The Sediment Stirred Up "],
["Turbulence", " Being Uncontrolled Violent "],
["Turgid", " Excessively Ornate Swollen Or Bloated"],
["Turmoil", " Trouble Disturbance "],
["Turpitude", " Wickedness Shamefulness "],
["Turquoise", " Greenish-blue Precious Stone"],
["Tyro", " Tiro Beginner "],
["Ubiquitous", " Present Everywhere "],
["Ulterior", " Situated Beyond "],
["Umbrage", " Offense Resentment "],
["Uncouth", " Rough Awkward "],
["Underbid", " Make A Lower Bid Then Somebody Else "],
["Undermine", " Weaken Gradually At The Base Make Something Under "],
["Undulate", " To Move In Wavelike Fashion Fluctuate "],
["Unearth", " Discover And Bring To Light "],
["Unencumbered", " Easy-going Trifle "],
["Unfeigned", " Not Pretended Sincere "],
["Unscathed", " Unharmed Unhurt "],
["Untoward", " Unfortunate Inconvenient "],
["Upbraid", " Scold Reproach "],
["Urbane", " Elegant Refined In Manners "],
["Vacillation", " Being Uncertain Hesitating "],
["Vagary", " Strange Act Or Idea "],
["Vain", " Without Use Result Conceited "],
["Valiant", " Brave "],
["Valorous", " Brave "],
["Vanquish", " Conquer "],
["Veer", " Change Direction "],
["Venal", " Ready To Do Something Dishonest"],
["Veneer", " Surface Appearance Covering The True Nature "],
["Veneration", " Regard With Deep Respect "],
["Veracity", " Truth "],
["Verdant", " Fresh And Green"],
["Verisimilitude", " Appearing True Or Real "],
["Veritable", " Real Rightly Named "],
["Verve", " Spirit Vigor Enthusiasm "],
["Vestige", " Trace Or Sign"],
["Vex", " Annoy Distress Trouble "],
["Vigilance", " Watchfulness Self-appointed Group Who Maintain Order "],
["Vigilant", " Member Of A Vigilance Committee"],
["Vigorous", " Strong Energetic "],
["Vilify", " Slander Say Evil Things "],
["Vindictive", " Having A Desire To Revenge"],
["Virago", " A Loud Domineering Woman A Scold Or Nag "],
["Visceral", " Of The Internal Organs Of The Body "],
["Viscous", " Sticky/semi-fluid "],
["Vitiate", " Lower The Quality Weaken The Strength "],
["Vituperate", " Curse Abuse In Words "],
["Vivacious", " Lively High-spirited "],
["Volatile", " Changeable Inconstant Fickle Unstable Explosive"],
["Volubility", " Fluency Verbosity Easy Use Of Spoken Language "],
["Voluble", " Fluent "],
["Waffle", " Talk Vaguely And Without Much Result "],
["Waft", " Scent Waving Movement Carry Lightly Through "],
["Wag", " Merry Person "],
["Warmonger", " Person Who Stirs Up War"],
["Warrant", " Authority Written Order Guarantee "],
["Wean", " To Turn Away (from A Habit) "],
["Weigh", " Measure Hoe Heavy Something Is"],
["Welter", " Turmoil A Bewildering Jumble "],
["Wend", " To Go Proceed "],
["Whimsical", " Full Of Odd And Fanciful Ideas "],
["Wince", " Show Bodily Or Mental Pain"],
["Woo", " Try To Win "],
["Writ", " Written Order "],
["Yarn", " Tale Story Fibers For Knitting"]
];











var length = WORDS.length;
var random = Math.floor(Math.random() * length);

var word = WORDS[random];

var wordDiv = document.getElementById('word');
var meaningDiv = document.getElementById('meaning');

var linkStr = "https://www.google.com/search?q=define+"+word[0];
// wordDiv.innerHTML = word[0];
wordDiv.innerHTML = "<a href="+linkStr+">"+word[0]+"</a>";
meaningDiv.innerHTML = word[1];















